#
# Title:        bash_logout
# Project:	Login
# Desc:
# 
#   
# 
# Notes:
# 
# Author:	Paul A. Houghton - (paul.houghton@wcom.com)
# Created:	01/15/97 08:08
#
# Revision History: (See end of file for Revision Log)
#
#   Last Mod By:    $Author$
#   Last Mod:	    $Date$
#   Version:	    $Revision$
#
#   $Id$
# 





#
# $Log$
# Revision 1.1  1997/01/15 15:17:23  houghton
# Initial Version.
#
#

# Local Variables:
# mode:ksh
# End:
