#
# Title:        bash_profile
# Project:	Login
# Desc:
# 
#   This script is run when bash is executed from 'login'. It also
#   runs the 'bashrc' script if the shell is interactive.
# 
# Notes:
# 
# Author:	Paul A. Houghton - (paul.houghton@wcom.com)
# Created:	01/15/97 08:08
#
# Revision History: (See end of file for Revision Log)
#
#   Last Mod By:    $Author$
#   Last Mod:	    $Date$
#   Version:	    $Revision$
#
#   $Id$
# 

export have_bash_profile=true


# Grab host specific profile if it exists

[ -f $HOME/.bash_${HOSTNAME}_profile ] &&
  source $HOME/.bash_${HOSTNAME}_profile

# set TOOL_DIR

if [ -n `eval echo \\${${PROJECT}_TOOL_DIR}` ] ; then
  
  eval export TOOL_DIR=\${${PROJECT}_TOOL_DIR}

  # set UTIL_DIR (only used when we have a PROJECT tool dir)
  utildirs="$host_util_dir /Tools /usr/local $HOME/tools"
  
  for dir in $utildirs ; do
    if [ -d $dir ] ; then
      export UTIL_DIR=$dir
      break
    fi
  done
  unset utildirs
  unset dir
  
else
  tooldirs="$host_tool_dir /Tools /ci/tools /usr/local $HOME/tools"

  for dir in $tooldirs ; do
    if [ -d $dir ] ; then
      export TOOL_DIR=$dir
      break
    fi
  done
  unset tooldirs
  unset dir
fi


#
# OPENWINHOME
#
[ -z "$OPENWINHOME" ] &&
[ -d "/usr/openwin" ] &&
export OPENWINHOME=/usr/openwin


# Sybase
syb_dirs="
  $TOOL_DIR/sybase
  $UTIL_DIR/sybase
  /opt/sybase
  /sybase/syb11
  /usr/sybase
"

for dir in $syb_dirs ; do
  if [ -d $dir ] ; then
    SYBASE=$dir
    break
  fi
done
unset syb_dirs
unset dir

if [ -n "$SYBASE" ] ; then
  export SYBASE
  export DSQUERY=DEV6_SQL
  export SYBSERV=DEV6_SQL
  export SYBDB="trfd_lookup_test"
  export SYBUSER="houghton"
  export SYBPASS
fi

#
# Cvs Env Setup
#
if [ `hostname` = "cworld" ] ; then
  export CVSROOT_cworld=/usr/src/Repository
else
  export CVSROOT_cworld=:pserver:houghton@cworld.wcom.com:/usr/src/Repository
fi

if [ `hostname` = "sideswipe" ] ; then
  export CVSROOT_sideswipe=/Tools/src/CvsRepository
else
  export CVSROOT_sideswipe=:pserver:houghton@sideswipe.wcom.com:/Tools/src/CvsRepository
fi

export CVSROOT=$CVSROOT_sideswipe

#
# Perl
#

if [ -d $HOME/scripts/perllib ] ; then
  if [ -n "$PERL5LIB" ] ; then
    export PERL5LIB=$HOME/scripts/perllib:$PERL5LIB
  else
    export PERL5LIB=$HOME/scripts/perllib
  fi
fi

#
# Gnu Info Env
#
[ -d /usr/info ] && INFOPATH=/usr/info
[ -d $UTIL_DIR/info ] && INFOPATH=$UTIL_DIR/info:$INFOPATH
[ -d $TOOL_DIR/info ] && INFOPATH=$TOOL_DIR/info:$INFOPATH
  
if [ -d $TOOL_DIR/lib/xemacs-20.4 ] ; then
  export INFOPATH=$TOOL_DIR/lib/xemacs-20.4/info:$INFOPATH
else
  if [ -d $TOOL_DIR/lib/xemacs-19.14 ] ; then
    export INFOPATH=$TOOL_DIR/lib/xemacs-19.14:$INFOPATH
  else
    export INFOPATH
  fi
fi

if [ -d $UTIL_DIR/lib/xemacs-20.4 ] ; then
  export INFOPATH=$UTIL_DIR/lib/xemacs-20.4/info:$INFOPATH
else
  if [ -d $UTIL_DIR/lib/xemacs-19.14 ] ; then
    export INFOPATH=$UTIL_DIR/lib/xemacs-19.14:$INFOPATH
  else
    export INFOPATH
  fi
fi

export REPLYTO="paul.houghton@wcom.com"

# Netscape
[ -d /usr/local/Netscape ] &&  MOZILLA_HOME=/usr/local/Netscape
[ -d /opt/netscape ]       && MOZILLA_HOME=/opt/netscape

if [ -n "$MOZILLA_HOME" ] ; then
  export MOZILLA_HOME
  export NPX_PLUGIN_PATH=$MOZILLA_HOME/plugins
  if [ -d /usr/local/Acrobat3/Browsers/intellinux ] ; then
    NPX_PLUGIN_PATH=$NPX_PLUGIN_PATH:/usr/local/Acrobat3/Browsers/intellinux
  fi
fi
  
# less
export LESS=-X

# Network News
export TRNINIT=$HOME/.trninit
export NEWSORG="WorldCom"

for cpp in /lib/cpp /bin/cpp /usr/bin/cpp ; do
  if [ -x $cpp ] ; then
    export IMAKECPP=$cpp
    break
  fi
done

#
# LD_LIBRARY_PATH
#

[ -f $HOME/.bash_setldlibpath ] && source $HOME/.bash_setldlibpath

#
# Setup my PATH
#

if [ `uname -s` = "SunOS"  ] ; then
  # Sun is strange
  PATH=/usr/bin:/bin
fi

# append other avaliable system dirs
append_dirs="/usr/ucb /usr/ccs/bin"
for ad in $append_dirs ; do
  [ -d $ad ] && PATH=$PATH:$ad
done
unset ad
unset append_dirs

# find X11 dirs if not already in path

if ! type xrdb > /dev/null 2>&1 ; then
  for xd in /usr/X11R6/bin /usr/bin/X11 /usr/openwin/bin ; do
    if [ -d $xd ] ; then
      PATH=$PATH:$xd
      break
    fi
    unset xd
  done
fi

# prepend available dirs
prepend_dirs=" /var/ldap/bin /usr/local/tex/bin"

cxx_dir_list="SC6.0 SC5.0 SC4.2"
for cxx_dir in $cxx_dir_list ; do
  if [ -d /opt/SUNWspro/$cxx_dir ] ; then
    prepend_dirs="$prepend_dirs /opt/SUNWspro/$cxx_dir/bin"
    break;
  fi
done

prepend_dirs="$prepend_dirs /usr/xpg4/bin"
[ -n "$SYBASE" ]    && prepend_dirs="$prepend_dirs $SYBASE/bin"
[ -n "$ORACLE_HOME" ]    && prepend_dirs="$prepend_dirs $ORACLE_HOME/bin"
[ -n "$UTIL_DIR" ]  && prepend_dirs="$prepend_dirs $UTIL_DIR/bin"
[ -n "$TOOL_DIR" ]  && prepend_dirs="$prepend_dirs $TOOL_DIR/bin"
prepend_dirs="$prepend_dirs $HOME/bin $HOME/scripts"

for pd in $prepend_dirs ; do
  [ -d $pd ] && PATH=$pd:$PATH
done
unset pd
unset prepend_dirs

PATH=.:$PATH

#
# Done with PATH (FINALLY!)
#

#
# MANPATH
#
case `man --version 2>&1` in
  *version\ 1.*)
    try_man_paths="
    /var/ldap/man
    /usr/local/tex/man
    "
    if ( [ -d /var/ldap/man ] || [ -d /usr/local/tex/man ] ) &&
      [ -z "$MANPATH" ] ; then
	MANPATH=`man -w`
    fi
    ;;
  *)
    for dir in `echo $PATH | sed -e 's@:@ @g' -e 's@/bin@@g' ` ; do
      mandir=$dir/man
      if [ $mandir != '.' -a -d $mandir ] ; then
	# echo $mandir
	try_man_paths="$try_man_paths $mandir"
      fi
    done

    for dir in `echo $MANPATH | sed -e 's@:@ @g'` ; do
      if [ $dir != '.' -a -d $dir ] ; then
	try_man_paths="$try_man_paths $dir"
      fi
    done

    unset dir
    unset mandir
    
    MANPATH=""
    
    try_man_paths="
    $try_man_paths
    $TOOL_DIR/lib/perl5/man
    "
    ;;
esac

for mp in $try_man_paths ; do
  if [ -d $mp ] ; then
    if [ -n "$MANPATH" ] ; then
      MANPATH="$MANPATH:$mp"
    else
      MANPATH=$mp
    fi
  fi
done
unset mp
unset try_man_paths

[ -n "$MANPATH" ] && export MANPATH

#
# Set or fix MAIL env vars
#
if [ -z "$MAIL" ] ; then
  if [ -d /var/spool/mail ] ; then
    export MAIL=/var/spool/mail/$USER
  else
    if [ -d /var/mail ] ; then
      export MAIL=/var/mail/$USER
    fi
  fi
fi

case $- in
  
  *i*)          # interactive
	[ -n "$have_bashrc" ] || source $HOME/.bashrc
	
	if [ -z "$DISPLAY" ] ; then

	  fromhost=`who -m | sed -e 's/.*:[0-9][0-9][ 	]*(*\([^):]*\).*/\1/'`
	  thishost=`hostname`
 
	  if [ -n "$fromhost" ] && [ "$fromhost" != "$thishost" ] ; then
    
	    read -p "Set DISPLAY to [hostname|none] (${fromhost}:0.0)? " disp
 
	    if [ -z "$disp" ] ; then
	      export DISPLAY=$fromhost:0.0
	    else
	      if [ $disp != "none" ] ; then
		export DISPLAY=$disp:0.0
	      fi
	    fi
	  fi
	fi

	if [ -n "$SYBSERV" ] ; then
	  read -p "Enter your password for $SYBSERV:$SYBUSER: " SYBPASS
	  export SYBPASS
	fi
	
        ;;
  *)
        ;;
esac


#if [ -n "$DISPLAY" -a -z "$XFILESEARCHPATH" ] ; then 
#   XFILESEARCHPATH=/usr/local/X11R6/lib/X11/%T/%N%C%S
#  XFILESEARCHPATH=$XFILESEARCHPATH:/usr/local/X11R6/lib/X11/%T/%N%S
#  XFILESEARCHPATH=$XFILESEARCHPATH:%D
#  export XFILESEARCHPATH
#fi



#
# $Log$
# Revision 1.29  2000/06/14 10:31:45  houghton
# Added ORACLE_HOME/bin to path.
#
# Revision 1.28  2000/06/09 17:12:28  houghton
# Added support for PROJECT variables
# Added support for host specific profile vars.
#
# Revision 1.27  1999/07/02 11:25:02  houghton
# Reworked SYBASE var.
#
# Revision 1.26  1999/06/22 12:27:20  houghton
# Added PERL5LIB env var.
#
# Revision 1.25  1999/06/17 16:22:13  houghton
# Added /var/ldap and /usr/local/tex to PATH and MANPATH
#
# Revision 1.24  1999/05/26 12:45:48  houghton
# Aded LESS env var.
#
# Revision 1.23  1999/05/21 10:21:00  houghton
# Changed: moved setting LD_LIBRARY_PATH to it's own file since it need
#          to be done by both basehrc and bash_provile.
#
# Revision 1.22  1999/05/13 12:32:46  houghton
# Fixed DSQUERY.
#
# Revision 1.21  1999/05/12 10:34:01  houghton
# Added sun compilter man dir to MANPATH.
#
# Revision 1.20  1999/05/04 09:28:49  houghton
# Changed Sybase server to DEV6_SQL
#
# Revision 1.19  1999/05/03 13:48:44  houghton
# Fixed TOOL_DIR and INFOPATH.
#
# Revision 1.18  1999/05/03 13:47:41  houghton
# Fixed Netscape directory.
#
# Revision 1.17  1999/05/02 12:15:56  houghton
# Fixed MANPATH
# Fixed LD_LIBRARY_PATH
# Fixed OPENWINHOME
#
# Revision 1.16  1999/05/01 14:01:04  houghton
# Fixed CVSROOT_sideswipe.
#
# Revision 1.15  1999/05/01 12:04:59  houghton
# Fixedup CVS env vars.
#
# Revision 1.14  1999/04/30 14:57:18  houghton
# Bug-Fix: missing then.
#
# Revision 1.13  1999/04/30 14:56:19  houghton
# Fixed SYBPASS when no sybase.
#
# Revision 1.12  1999/04/30 14:54:54  houghton
# BugFix fromhost variable.
#
# Revision 1.11  1999/04/30 14:29:24  houghton
# Many fixes for SunOS
#
# Revision 1.10  1999/04/29 20:53:47  houghton
# Fixed path to X11 bin
#
# Revision 1.9  1999/04/28 23:04:03  houghton
# Fixed TOOL_DIR and PATH.
#
# Revision 1.8  1999/04/28 09:22:14  houghton
# Fixed netscape vars.
#
# Revision 1.7  1999/04/28 09:12:55  houghton
# Merge with cmore changes.
#
# Revision 1.6  1999/04/25 06:32:57  houghton
# Fix infopath (again).
#
# Revision 1.5  1999/04/25 06:32:02  houghton
# Fix infopath.
#
# Revision 1.4  1999/04/25 06:29:11  houghton
# Major rework
#
# Revision 1.3  1997/04/05 12:15:08  houghton
# Added Motif bin to PATH
# Added /usr/local/lib/beta to LD_LIBRARY path
#
# Revision 1.2  1997/01/15 15:20:49  houghton
# Added comments.
#
# Revision 1.1  1997/01/15 15:17:23  houghton
# Initial Version.
#
#

# Local Variables:
# mode:ksh
# End:

