#
# File:		kshrc
# Project:	LoginUtils 
# Desc:
#
#   
#
# Notes:
#
# Author(s):   Paul Houghton <paul4hough@gmail.com>
# Created:     06/04/2003 22:23
#
# Revision Info: (See ChangeLog or cvs log for revision history)
#
#	$Author$
#	$Date$
#	$Name$
#	$Revision$
#	$State$
#
# $Id$
#

case $- in
  *i*)
    PS1="@host_name@\$ "
    stty erase 
    ;;
  *)
    ;;
esac


# Local Variables:
# mode:ksh
# End:
