# xinitrc - 2014-02-16 19:15
#
# Copyright (c) 2014 Paul Houghton <paul4hough@gmail.com>
#
echo XINITRC ***
[ -f ~/.xmodmap ] && xmodmap ~/.xmodmap
[ -f ~/.Xdefaults ] && xrdb ~/.Xdefaults
freq=600 # 10 min
~/scripts/rand_wallpaper $freq &
bgpid=$!
echo BG Desk $bgpid
fvwm2
kill $bgpid
# Local Variables:
# mode:sh
# End:
